.PHONY: all Q_1 Q_2 Q_3 Q_4 Q_5 Q_6 Q_7 clean

all: Q_1 Q_2 Q_3 Q_4 Q_5 Q_6 Q_7

Q_1: division_by_zero infinite_Recursion_Error UndefinedUseInMEM

division_by_zero:
	$(MAKE) -C Q_1/division_by_zero

infinite_Recursion_Error:
	$(MAKE) -C Q_1/Infinite_Recursion_Error

UndefinedUseInMEM:
	$(MAKE) -C Q_1/UndefinedUseInMEM

Q_2:
	$(MAKE) -C Q_2

Q_3:
	$(MAKE) -C Q_3

Q_4:
	$(MAKE) -C Q_4

Q_5:
	$(MAKE) -C Q_5

Q_6:
	$(MAKE) -C Q_6

Q_7:
	$(MAKE) -C Q_7

clean:
	$(MAKE) -C Q_1/division_by_zero clean
	$(MAKE) -C Q_1/Infinite_Recursion_Error clean
	$(MAKE) -C Q_1/UndefinedUseInMEM clean
	$(MAKE) -C Q_2 clean
	$(MAKE) -C Q_3 clean
	$(MAKE) -C Q_4 clean
	$(MAKE) -C Q_5 clean
	$(MAKE) -C Q_6 clean
	$(MAKE) -C Q_7 clean
